kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"bamoe-canvas-ui:9.3.0-ibm-0007"},"fieldPath":"spec.template.spec.containers[?(@.name==\"bamoe-canvas-ui\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '9380188'
  name: bamoe-canvas-ui
  uid: 4daa60aa-7d1d-46bf-8a5b-d32327690e71
  creationTimestamp: '2025-10-12T17:00:39Z'
  generation: 2
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-12T17:00:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"bamoe-canvas-ui"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"KIE_SANDBOX_CORS_PROXY_URL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"KIE_SANDBOX_EXTENDED_SERVICES_URL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kubectl-label
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-12T17:00:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-12T17:00:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"bamoe-canvas-ui"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-10-12T17:00:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: bamoe-v930
  labels:
    app: bamoe-canvas-ui
    app.kubernetes.io/component: bamoe-canvas-ui
    app.kubernetes.io/instance: bamoe-canvas-ui
    app.kubernetes.io/part-of: bamoe-v930
    app.openshift.io/runtime: js
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: bamoe-canvas-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: bamoe-canvas-ui
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: bamoe-canvas-ui
          image: 'quay.io/bamoe/canvas@sha256:240ad0c3ac1c9b7263e353393c17062fd6fbb1bd4429046a1d69d6bf9b38da23'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KIE_SANDBOX_CORS_PROXY_URL
              value: 'https://bamoe-canvas-cors-proxy-bamoe-v930.apps-crc.testing'
            - name: KIE_SANDBOX_EXTENDED_SERVICES_URL
              value: 'https://bamoe-canvas-extended-services-bamoe-v930.apps-crc.testing'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-10-12T17:00:45Z'
      lastTransitionTime: '2025-10-12T17:00:45Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-10-12T17:00:45Z'
      lastTransitionTime: '2025-10-12T17:00:39Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "bamoe-canvas-ui-6595866555" has successfully progressed.
